AWSTemplateFormatVersion: "2010-09-09"
Description: "contentful space backup"

Resources:
  ContentfulBackupS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub contentful-backup-${AWS::AccountId}
      #BucketName: contentful-backup-123
      LifecycleConfiguration:
        Rules:
        - Id: RetentionRule
          Status: Enabled
          ExpirationInDays: '30'